export const FIRST_NAMES = [
  "Aarav",
  "Aditi",
  "Ananya",
  "Arjun",
  "Diya",
  "Ishaan",
  "Kavya",
  "Rohan",
  "Sneha",
  "Vihaan",
  "Meera",
  "Kabir",
  "Pooja",
  "Rahul",
  "Neha",
  "Amit",
  "Priya",
  "Sanjay",
  "Anjali",
  "Vikram",
  "Shreya",
  "Nikhil",
  "Isha",
  "Manish",
  "Ritu",
  "Harsh",
  "Tanvi",
  "Dev",
  "Nisha",
  "Karan",
  "Sonia",
  "Rajesh",
  "Deepa",
  "Mohit",
  "Ankita",
  "Suresh",
  "Lakshmi",
  "Farhan",
  "Zara",
  "Imran",
  "Fatima",
  "Joseph",
  "Maria",
  "Thomas",
  "Aisha",
  "Ravi",
  "Sunita",
  "Gaurav",
  "Pallavi",
  "Yash",
  "Kriti",
  "Abhishek",
  "Swati",
  "Naveen",
  "Divya",
  "Pranav",
  "Rhea",
  "Siddharth",
  "Anushka",
  "Varun",
] as const;

export const LAST_NAMES = [
  "Sharma",
  "Patel",
  "Singh",
  "Kumar",
  "Gupta",
  "Reddy",
  "Nair",
  "Iyer",
  "Mehta",
  "Joshi",
  "Khan",
  "Das",
  "Banerjee",
  "Chopra",
  "Malhotra",
  "Verma",
  "Rao",
  "Naidu",
  "Pillai",
  "Desai",
  "Agarwal",
  "Jain",
  "Kapoor",
  "Bhat",
  "Shetty",
  "Ghosh",
  "Mukherjee",
  "Chatterjee",
  "Pandey",
  "Mishra",
  "Yadav",
  "Choudhary",
  "Bose",
  "Menon",
  "Kulkarni",
  "Patil",
  "Fernandes",
  "D'Souza",
  "Ahmed",
  "Qureshi",
] as const;

export const SMB_TRADE_NAMES = [
  "Nexus",
  "Summit",
  "Vertex",
  "Harbor",
  "Lotus",
  "Saffron",
  "Monsoon",
  "Cedar",
  "Indigo",
  "Cobalt",
  "Orchid",
  "Maple",
  "Pinnacle",
  "Horizon",
  "Ember",
] as const;

export const SMB_SUFFIXES = [
  "Traders",
  "Supplies",
  "Logistics",
  "Foods",
  "Textiles",
  "Electronics",
  "Clinics",
  "Studios",
  "Workshops",
  "Retail",
  "Services",
  "Labs",
] as const;

export const ENT_NAMES = [
  "Meridian Hospitals Pvt Ltd",
  "Deccan Steel & Alloys Ltd",
  "Coastal Freight India Ltd",
  "Northern Grid Power Ltd",
  "Sahyadri Agro Processing Ltd",
  "BlueRidge IT Services Ltd",
  "Ganga Pharma Labs Ltd",
  "Eastern Ports Authority Co",
  "Vindhya Minerals Ltd",
  "Sundarban Logistics Ltd",
  "Kaveri Dairy Cooperative Ltd",
  "Aravalli Cement Works Ltd",
  "Pampa Energy Holdings Ltd",
  "Chola Auto Components Ltd",
  "Narmada Water Infra Ltd",
  "Himalaya Tea Estates Ltd",
  "Konkan Marine Foods Ltd",
  "Malabar Spice Exports Ltd",
  "Yamuna Urban Housing Ltd",
  "Godavari Cotton Mills Ltd",
  "Thar Renewables Ltd",
  "Sutlej Paper & Board Ltd",
  "Anamalai Plantations Ltd",
  "Coromandel Shipping Ltd",
  "Rajputana Hotels Ltd",
  "Bengal Chemical Works Ltd",
  "Mysore Silk Park Ltd",
  "Punjab Agri Commodities Ltd",
  "Goa Shipyard Vendors Ltd",
  "Udaipur Marble Exports Ltd",
  "Assam Tea Logistics Ltd",
  "Bhopal Precision Tools Ltd",
  "Coimbatore Pump Works Ltd",
  "Vizag Pellet Terminal Ltd",
  "Jaipur Crafts Wholesale Ltd",
  "Lucknow Diagnostic Chain Ltd",
  "Patna Grain Exchange Ltd",
  "Ranchi Mining Services Ltd",
  "Guwahati River Transport Ltd",
  "Shimla Hill Resorts Ltd",
  "Nagpur Orange Coldchain Ltd",
  "Surat Diamond Facets Ltd",
  "Indore Pharma Distributors Ltd",
  "Kanpur Leather Houses Ltd",
  "Madurai Temple Foods Ltd",
  "Trivandrum MedTech Ltd",
  "Bhubaneswar Port Stores Ltd",
  "Amritsar Textile Hub Ltd",
  "Vadodara Chemical Park Ltd",
  "Nashik Vineyard Co Ltd",
  "Jodhpur Solar Parks Ltd",
  "Agra Heritage Hotels Ltd",
  "Varanasi Silk Weaves Ltd",
  "Chandigarh IT Parks Ltd",
  "Faridabad Auto Ancillary Ltd",
  "Noida Data Centres Ltd",
  "Gurgaon Facility Mgmt Ltd",
  "Pune EV Components Ltd",
  "Hyderabad Genome Labs Ltd",
  "Bengaluru Cloud Ops Ltd",
] as const;
